-- yun-seeker minimal schema

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  email text not null,
  birth_date text not null,
  birth_time text not null,
  birth_place text not null,
  current_location text,
  timezone text not null default 'Asia/Hong_Kong',
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_uq on public.profiles(email);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  email text not null,
  asked_at timestamptz not null,
  title text not null,
  question text not null,
  summary text,
  confidence text,
  focus text,
  highlights jsonb,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists reports_email_idx on public.reports(email);
create index if not exists reports_asked_at_idx on public.reports(asked_at desc);

-- Recommended for production: enable RLS and add per-user policies.
